name: sfp
channels:
  - conda-forge
  - nvidia
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - pip
  - numpy>=1.21.5,<1.22
  - matplotlib=3.5.3
  - scipy
  - seaborn>=0.12,<0.13
  - pandas=1.3.5
  - pyyaml
  - h5py=2.10
  - nibabel
  - scikit-learn
  - snakemake>=5.32,<5.33
  - tqdm
  - pip:
      - neuropythy
