name: sfp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.7
  - pytorch
  - pip
  - numpy
  - matplotlib
  - scipy
  - seaborn>=0.12,<0.13
  - pandas
  - pyyaml
  - h5py
  - nibabel
  - scikit-learn
  - snakemake>=5.32,<6.0
  - tqdm
  - tables
  - pip:
      - neuropythy
